CREATE TABLE [dbo].[TeamData] (
    [id]               INT             IDENTITY (1, 1) NOT NULL,
    [lid]              INT             NOT NULL,
    [Team]             VARCHAR (20)    NULL,
    [Rank]             TINYINT         NULL,
    [Win]              TINYINT         NULL,
    [Draw]             TINYINT         NULL,
    [Lose]             TINYINT         NULL,
    [Goal]             TINYINT         NULL,
    [Goal_Rank]        TINYINT         NULL,
    [AntiGoal]         TINYINT         NULL,
    [AntiGoal_Rank]    TINYINT         NULL,
    [Pts]              TINYINT         NULL,
    [Shoot]            INT             NULL,
    [Shoot_Rank]       TINYINT         NULL,
    [HeadShoot]        INT             NULL,
    [Pass]             INT             NULL,
    [Pass_Rank]        TINYINT         NULL,
    [ThreadPass]       INT             NULL,
    [ThreadPass_Rank]  TINYINT         NULL,
    [Cross]            INT             NULL,
    [Cross_Rank]       TINYINT         NULL,
    [Steal]            INT             NULL,
    [Steal_Rank]       TINYINT         NULL,
    [Foul]             INT             NULL,
    [Foul_Rank]        TINYINT         NULL,
    [Be_Shoot]         INT             NULL,
    [Be_Shoot_Rank]    TINYINT         NULL,
    [FreeKick]         INT             NULL,
    [FreeKick_Rank]    CHAR (2)        NULL,
    [OffSide]          INT             NULL,
    [OffSide_Rank]     TINYINT         NULL,
    [ControlRate]      NUMERIC (18, 2) NULL,
    [ControlRate_Rank] TINYINT         NULL,
    [CornerKick]       INT             NULL,
    [CornerKick_Rank]  TINYINT         NULL,
    [Year]             SMALLINT        NULL,
    CONSTRAINT [PK_TeamData] PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [FK_TeamData_League] FOREIGN KEY ([lid]) REFERENCES [dbo].[League] ([lid])
);

