<table class="twidth" align=center cellpadding=0 cellspacing=0 border=0>
<tr><td class="sitehead-left">
</td><td class="sitehead">
	<table align=center width=100% >
	<tr><td width=200>
	<a href="<%=myConst.SiteUrl%>"><%=myConst.Logo%></a>
	</td>
	<td align=center>
	<%=myConst.HeadAd%>
	</td>
	<td width=100 align=center style="line-height:150%">
	<a href=# onclick="javascript:window.external.addFavorite('<%=myConst.SiteUrl%>','<%=myConst.SiteName%>')"><%=lang["add_favorite"]%></a>
	<br>
	<a href="mailto:<%=myConst.SiteEmail%>"><%=lang["contact_us"]%></a>
	<br>
	<a href="admin_login.aspx" target=_blank><%=lang["login_admin"]%></a>
	</td>
	</tr>
	</table>
</td><td class="sitehead-right">
</td></tr>
</table>
